require("core.options")
require("core.keymaps")
require("core.autocmds")

-- Load all plugins natively (pre-installed by Nix into runtimepath)
require("plugins.alpha")
-- require("plugins.auto-save")
require("plugins.colorscheme")
require("plugins.completion")
require("plugins.conform")
require("plugins.git")
require("plugins.lsp")
require("plugins.lualine")
require("plugins.luasnip")
require("plugins.none-ls")
require("plugins.nvim-tree")
require("plugins.oil")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.utils")
require("plugins.zen-mode")
