name: workflow run cleanup
on:
  workflow_dispatch:
  schedule:
    - cron: '30 18 * * 0'
# Workflow permissions
permissions:
  actions: write
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: clean workflow runs
        uses: boredland/action-purge-workflow-runs@main
        with:
          days-old: 14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
